version: '3.4'

services:
  messagequeue.web:
    image: ${DOCKER_REGISTRY-}messagequeueweb
    build:
      context: .
      dockerfile: MessageQueue.Web/Dockerfile
  

  messagequeue.book:
    image: ${DOCKER_REGISTRY-}messagequeuebook
    build:
      context: .
      dockerfile: MessageQueue.Book/Dockerfile
    

  messagequeue.cart:
    image: ${DOCKER_REGISTRY-}messagequeuecart
    build:
      context: .
      dockerfile: MessageQueue.Cart/Dockerfile
    

  distributedcache:
    image: redis
  
  nginx:
    image: nginx
  messagebroker:
    image: rabbitmq:management