version: '3.4'

services:
  messagequeue.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Redis=distributedcache:6379
    ports:
      - "5050:8080"
      - "5051:8081"
      
    depends_on:
       - distributedcache
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
        - "6379:6379"
    
  messagequeue.book:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Redis=distributedcache:6379
    ports:
      - "6000:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - messagebroker
  messagequeue.cart:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Redis=distributedcache:6379
    ports:
      - "7070:8080"
      - "7071:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - messagebroker
  nginx:
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Nginx/library.com+4.pem:/etc/nginx/ssl/library.pem
      - ./Nginx/library.com+4-key.pem:/etc/nginx/ssl/library.key
      - ./files:/usr/share/nginx/html
    depends_on:
      - messagequeue.web
      - messagequeue.book 
    restart: always

  messagebroker:
    container_name: messagebroker
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  postgresql-master:
    container_name: postgresql-master
    ports:
      - '5432:5432'

    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=librarydatabase
    restart: always
    volumes:
      - postgres_library:/var/lib/postgresql/data/ 